spring:
  application:
    name: fireball-world
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/fireball
    username: fireball
    password: fireball
    driver-class-name: org.postgresql.Driver

netty:
  port: 8085
  boss-threads: 1
  worker-threads: 0

#logging:
#  level:
#    root: debug
