services:
  postgres:
    image: postgres:17
    container_name: fireball-db
    environment:
      POSTGRES_DB: fireball
      POSTGRES_USER: fireball
      POSTGRES_PASSWORD: fireball
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: